version: "3.8"
services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  leapcoin-voting-api:
    image: hussu010/leapcoin-voting-api
    env_file: .env