version: "3.9"
services:
  leapcoin-voting-api:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://leapcoin:leapcoin@mongo:27017/?authSource=admin
    command: npm run dev
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=leapcoin
      - MONGO_INITDB_ROOT_PASSWORD=leapcoin
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: