name: Deploy to deta once pushed to staging

on:
  push:
    branches:
      - staging

env:
  STAGING_MONGO_URI: ${{ secrets.STAGING_MONGO_URI }}
  STAGING_JWT_SECRET_KEY: ${{ secrets.STAGING_JWT_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }}
          deta-name: ${{ secrets.STAGING_DETA_MICRO }}
      - run: |
          # Create .env
          echo "STAGING_MONGO_URI=${{ env.STAGING_MONGO_URI }}" | tee -a .env > /dev/null
          echo "STAGING_JWT_SECRET_KEY=${{ env.STAGING_JWT_SECRET_KEY }}" | tee -a .env > /dev/null
          # Deploy environment variables
          export DETA_ACCESS_TOKEN=${{ secrets.DETA_ACCESS_TOKEN }}
          ~/.deta/bin/deta update -e .env
